.global sprite_data
.global sprite_data_end

.global player_bullet_sprite_data
.global player_bullet_sprite_data_end
.global enemy_bullet_sprite_data
.global enemy_bullet_sprite_data_end
.global player_sprite_data
.global player_sprite_data_end
.global enemy_sprite_data
.global enemy_sprite_data_end
.global explosion_sprite_data
.global explosion_sprite_data_end
.global skull_sprite_data
.global skull_sprite_data_end

.global letter_sprite_data
.global letter_sprite_data_end

.global d_sprite_data
.global d_sprite_data_end
.global a_sprite_data
.global a_sprite_data_end
.global m_sprite_data
.global m_sprite_data_end
.global o_sprite_data
.global o_sprite_data_end
.global n_sprite_data
.global n_sprite_data_end
